parser: '@typescript-eslint/parser'
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
plugins:
  - react
  - '@typescript-eslint'
settings:
  react:
    version: detect
parserOptions:
  ecmaFeatures:
    jsx: true
rules:
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  no-undef: 'off'
  react/self-closing-comp: 'warn'
